### PR TITLE
Linked EditProfile to Database

### PR DESCRIPTION
**Pull request by nmdoran**
This branch updates the edit profile feature.
1) Adds a function to check if there is data in at least one field.
2) Updates the database with whichever fields have data inputted.

Testing Done:
1) Input data into 1, 2 or 3 fields to test validate() function that looks if data is inputted.
2) Input data in the wrong format (Hiba's data validation from last sprint) and check for error pop ups.
3) Check data is properly updated in database when 1, 2 or 3 fields have data.

Currently, when the form is submitted, the users stays on the edit profile page and the data is shown to be updated in the boxes.  Is this what we want or should it redirect them to the home page?

### CODE REVIEW

**Comment by nmdoran** [comment]
One additional note: I removed the email frequency setting since it wasn't working and Palak said that we weren't using that in the email functionality anyways.  Please let me know if this is a concern for anyone.

**Comment by miralsumrani** [comment]
When I tested this functionality, I changed the fields to "Miral Sumrani," "sumranimiral@gmail.com," and "L6X 5C5," and only the name field was updated. No other areas were updated, and the email in the boxes are still "n.doran99@gmail.com," and "A1A 1A1." Is this supposed to happen?

**Comment by mishrapalak** [comment]
Thanks for working on this Nicole! When I tested this, I entered new information and clicked edit profile. The form only shows changes to the Name and not the email ID or postal code. But when I go back to Homepage and come back to Edit Profile, everything is updated. I think this can be fixed by first redirecting the user to Homepage instead of back to Edit Profile and have a pop-up saying "Your information has been updated". This way when they go back to Edit Profile, it should all be updated. 
Also it would be great if you could add a hyperlink on the main page to get to the edit profile page. Apart from that, great work!

**Comment by nmdoran** [comment]
Thanks for the feedback guys.  The database was updating but for some reason only one field showed as edited.  I've fixed this by refreshing the page so it shows all fields are updated as well as adding a pop up message. I've also added a link to edit profile from the main page.

**Comment by mishrapalak** [comment]
Thank you for making all the changes! It works perfectly now, great work!! 
I have tested 3 different profiles 
- testing edit , testing@gmail.com, T1T 1T2
- palak mishra, palak@gmail.com, N2L 3V1
- john doe, johndoe@gmail.com, X2C 4H5
and they all give me a pop up and refresh the page with all the changes. It is good to merge

**Pull request merged**
