### PR TITLE
Change font

### PR DESCRIPTION
**Pull request by Alikpld**
This pull request changes the font of all the pages to "Times New Roman"  to keep the font of the overall tool consistent.

I faced some issues as i thought just changing the body part of the pages should automatically change all the content to the same font but I had to manually go to some buttons/dropdowns and add the style. For anyone reviewing the code if you find some redundancy please let me know if there's a better way to do this :)

Also if anyone prefers another font please mention it here or during the standup and i'll gladly change if the team agrees on a specific one!

Thanks!

### CODE REVIEW

**Comment by nmdoran** [comment]
Could we not do Times New Roman?  (Sorry I know you asked for suggestions and we said do whatever)  I feel like it's so formal. I suggest Helvetica or another sans-serif font.

**Comment by miralsumrani** [comment]
I agree with Nicole, better website design fonts may be Open Sans or Georgia. Perhaps look into those fonts as well.

**Comment by Alikpld** [comment]
Thanks guys @miralsumrani  @nmdoran , I changed it to Georgia! :)

**Comment by nmdoran** [comment]
Looks good to me.  Thanks Alik!

**Pull request merged**
