### PR TITLE
edit and delete button and popup

### PR DESCRIPTION
**Pull request by nandatanvi**
i added edit and delete button to the table on the main page and added a popup, the form still needs to be added.

### CODE REVIEW

**Comment by hibatawfeeq** [comment]
Great work!

The popups work perfectly, I tried it as well. Just one minor comment for lines 139-146 on "index.js" file, it would be great if we can keep all JS functions in one file "client.js". The reason why is because we could keep track of all functions there instead of having it in multiple places, in case we need to use it somewhere else or make edits. That way it's easier to find and reuse, instead of creating a new one.

Hope this makes sense! Otherwise feel free to let me know and I'll be happy to explain further.

**Comment by mishrapalak** [comment]
Good job on the code! The pop-up works well and it very intuitive. The delete button works well, but the edit functionality has some issues when I try to save the changes I make. This is what I get, you might want to check out why this is happening. Feel free to reach out if you need any help resolving it!
Screen Shot 2020-11-22 at 8 33 43 PM

**Comment by nandatanvi** [comment]
> Great work!
> 
> The popups work perfectly, I tried it as well. Just one minor comment for lines 139-146 on "index.js" file, it would be great if we can keep all JS functions in one file "client.js". The reason why is because we could keep track of all functions there instead of having it in multiple places, in case we need to use it somewhere else or make edits. That way it's easier to find and reuse, instead of creating a new one.
> 
> Hope this makes sense! Otherwise feel free to let me know and I'll be happy to explain further.

**Comment by nandatanvi** [comment]
> Great work!
> 
> The popups work perfectly, I tried it as well. Just one minor comment for lines 139-146 on "index.js" file, it would be great if we can keep all JS functions in one file "client.js". The reason why is because we could keep track of all functions there instead of having it in multiple places, in case we need to use it somewhere else or make edits. That way it's easier to find and reuse, instead of creating a new one.
> 
> Hope this makes sense! Otherwise feel free to let me know and I'll be happy to explain further.

Thanks Hiba! I will make this change :)

**Comment by nandatanvi** [comment]
> Good job on the code! The pop-up works well and it very intuitive. The delete button works well, but the edit functionality has some issues when I try to save the changes I make. This is what I get, you might want to check out why this is happening.
> Screen Shot 2020-11-22 at 8 33 43 PM

Thanks Palak! Im getting the same error too! Im working on resolving this and also completeing the functionality of the edit button

**Comment by mdschnei** [comment]
Great work, looks like everything has been ironed out now! Merging!

**Pull request merged**
