### PR TITLE
basic scroll bar connected to HTML table

### PR DESCRIPTION
**Pull request by miralsumrani**
The scroll bar feature was added to the HTML table, to ensure that the length of the table would not interfere with the rest of the page. 

Adding/deleting items was done for testing, to ensure that the scrollbar only appears when it is needed, which is when the products start "overflowing."

### CODE REVIEW

**Comment by Alikpld** [comment]
Great work on adding the scroll bar! 
I think there is a conflict in index.ejs but it shouldn't be a big issue we can solve it before we merge to main

**Comment by mishrapalak** [comment]
Good job on the scroll bar! It makes the entire appearance of the webpage much better. As Alik mentioned, there is a small conflict in the index.ejs file but this should be resolved easily when we finally merge it!

**Comment by miralsumrani** [comment]
> Good job on the scroll bar! It makes the entire appearance of the webpage much better. As Alik mentioned, there is a small conflict in the index.ejs file but this should be resolved easily when we finally merge it!

> Great work on adding the scroll bar!
> I think there is a conflict in index.ejs but it shouldn't be a big issue we can solve it before we merge to main

The conflicts are resolved! It's good to go now.

**Comment by mishrapalak** [comment]
Thank you for resolving them! This branch is good to merge now. :)

**Pull request merged**
