### PR TITLE
conducted testing on edit feature

### PR DESCRIPTION
**Pull request by nandatanvi**
**Test Cases for Edit Button:**

- empty inputs for both expiry and quantity: site send the user an error message "Please add values for one or more of the fields" 

Edit Expiry Date: 

- only accepts dates in the format "yyyy-mm-dd"
- only accepts numeric values (if the user types in letters or any other characters, they are not inputted in the date field)
- only accepts positive numeric values 

Edit Quantity: 

- only accepts numeric values (if the user types in letters or any other characters, they are not inputted in the date field)
- does not accept negative values for quantity

"Done" Button:

- sends user confirmation message "Successfully Edited"

"Cancel" Button:

- makes no changes to the user's fridge table

**Delete button:**

- sends user confirmation message "Successfully Edited"
- does not require any testing as this button does not take any input from users.

### CODE REVIEW

**Comment by nmdoran** [comment]
Did you run tests with data in expiry date and quantity, as well as both fields individually?

**Comment by nandatanvi** [comment]
> Did you run tests with data in expiry date and quantity, as well as both fields individually?

Yes I did

**Comment by nandatanvi** [comment]
Added final feature to the edit and delete button feature (option to edit product type). 

**More Test Cases:**

- The site only allows Custom product's types to be edited. 
- Type/expiry date/quantity can be edited at the same time (or any combination of the three)
- The product type field can not be left blank

**Comment by Alikpld** [comment]
Great work! I just tested these and they all display the error handling messages!
Merging to main :)

**Pull request merged**
